# Generated by Django 5.0.1 on 2024-01-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
